version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  runestone:
    image: runestone/server
    command: tail -F peanutbutter
    volumes:
      - .:/code
      - ./docker/uwsgi.ini:/etc/uwsgi/uwsgi.ini
      - ./docker/uwsgi-emperor.conf:/etc/init/uwsgi-emperor.conf
    links:
      - db
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  nginx:
    restart: always
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/uwsgi_params.par:/etc/nginx/uwsgi_params.par
      - ./docker/web2py.xml:/etc/uwsgi/web2py.xml
    links:
      - runestone
      - db
