version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  runestone:
    image: runestone/server
    #command: tail -F peanutbutter
    volumes:
      - .:/code
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
