name: Mark stale issues and pull requests

on:
    workflow_dispatch:
        inputs:
            description: "Who is running"
            required: false
            default: "Brad"

jobs:
    stale:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/stale@v3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-stale: 90
                  stale-issue-message: "Stale issue message"
                  stale-pr-message: "Stale pull request message"
                  stale-issue-label: "no-issue-activity"
                  stale-pr-label: "no-pr-activity"
